#3 add bootstrap to the user.html file
Zfitmeta/Mentoring pull request #6
Opened 2022-05-16 14:27 UTC by Zfitmeta

@francoiscrouzet Kindly check.
Thanks

2022-05-16 15:55 UTC, francoiscrouzet commented
@Zfitmeta hi! Please remove the screenshot from the repo, add it to the issue, and we're good!

2022-05-16 15:56 UTC, francoiscrouzet requested changes
@Zfitmeta hi! Please remove the screenshot from the repo, add it to the issue, and we're good!

2022-05-17 07:16 UTC, Zfitmeta commented
@francoiscrouzet deleted the screenshot from the repo and added it to the issue in the comment section.
Thanks.

2022-05-17 07:33 UTC, francoiscrouzet approved these changes

2022-05-17 07:33 UTC, merged